pipeline:
  lint_troposphere:
    image: python:3.7-alpine
    commands:
      - apk add --no-cache gcc musl-dev make
      - python3 -m venv venv
      - source venv/bin/activate
      - pip install -r requirements.txt
      - make tropo-lint
      - deactivate
    when:
      event:
        - push
        - tag

  test_troposphere:
    image: python:3.7-alpine
    commands:
      - apk add --no-cache make
      - source venv/bin/activate
      - make tropo-test
      - deactivate
    when:
      event:
        - push
        - tag

  test_nodejs:
    image: node:8-alpine
    commands:
      - apk add make
      - make node-test
    when:
      event:
        - push
        - tag
